# Use the official Caddy image as the base image
FROM caddy:2.8.4

# Create a group with GID 1000 and a user with UID 1000
RUN addgroup --gid 1000 appgroup && adduser --uid 1000 --gid 1000 --disabled-password --gecos "" appuser

# Set permissions for non root user in directories we will need
RUN mkdir -p /data && chown -R 1000:1000 /data


# Copy the Caddyfile from the host to the container
COPY Caddyfile /etc/caddy/Caddyfile