FROM ollama/ollama:latest

# Create a group with GID 1000 and a user with UID 1000
RUN addgroup --gid 1000 appgroup && adduser --uid 1000 --gid 1000 --disabled-password --gecos "" appuser

# set permission for non root to ollama directory
RUN mkdir -p /.ollama && chown -R 1000:1000 /.ollama

# copy the entrypoint script. This is what the container will run when it starts.
COPY ./ollama-entrypoint.sh ollama-entrypoint.sh